#  Dockerfile for Node Express Backend

FROM node:22-alpine

# Create App Directory
RUN mkdir -p ./app 
WORKDIR /usr/app

# Install Dependencies
COPY package*.json ./

RUN npm install --silent

# Copy app source code
COPY . .

# Exports
EXPOSE 4000

CMD ["npm","start"]